DROP DATABASE IF EXISTS burgerDB;
CREATE DATABASE burgerDB;

USE burgerDB;

CREATE TABLE burgers
(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    eaten BOOLEAN DEFAULT false
);